/*
 * This file was automatically generated by EvoSuite
 */

package org.saxpath.helpers;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.saxpath.SAXPathException;
import org.saxpath.helpers.DefaultXPathHandler;

@RunWith(EvoSuiteRunner.class)
public class DefaultXPathHandlerEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endXPath();
  }

  @Test
  public void test1()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startEqualityExpr();
  }

  @Test
  public void test2()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endRelativeLocationPath();
  }

  @Test
  public void test3()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endPathExpr();
  }

  @Test
  public void test4()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endFilterExpr();
  }

  @Test
  public void test5()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endAdditiveExpr(1744);
  }

  @Test
  public void test6()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startOrExpr();
  }

  @Test
  public void test7()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endAllNodeStep();
  }

  @Test
  public void test8()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startAndExpr();
  }

  @Test
  public void test9()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.variableReference("Uc31x%_3TT-O}Rq]L", "Uc31x%_3TT-O}Rq]L");
  }

  @Test
  public void test10()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.literal("");
  }

  @Test
  public void test11()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endRelationalExpr(1);
  }

  @Test
  public void test12()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startNameStep(0, "tMO&<6h}+", "tMO&<6h}+");
  }

  @Test
  public void test13()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startFunction("root case:", "root case:");
  }

  @Test
  public void test14()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endUnionExpr(true);
  }

  @Test
  public void test15()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startFilterExpr();
  }

  @Test
  public void test16()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startTextNodeStep(0);
  }

  @Test
  public void test17()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endMultiplicativeExpr(0);
  }

  @Test
  public void test18()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endProcessingInstructionNodeStep();
  }

  @Test
  public void test19()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startRelationalExpr();
  }

  @Test
  public void test20()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endOrExpr(false);
  }

  @Test
  public void test21()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endNameStep();
  }

  @Test
  public void test22()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startPredicate();
  }

  @Test
  public void test23()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endUnaryExpr(1);
  }

  @Test
  public void test24()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endAbsoluteLocationPath();
  }

  @Test
  public void test25()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startXPath();
  }

  @Test
  public void test26()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startCommentNodeStep(1);
  }

  @Test
  public void test27()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startAdditiveExpr();
  }

  @Test
  public void test28()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startAbsoluteLocationPath();
  }

  @Test
  public void test29()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startMultiplicativeExpr();
  }

  @Test
  public void test30()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endTextNodeStep();
  }

  @Test
  public void test31()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endCommentNodeStep();
  }

  @Test
  public void test32()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endAndExpr(true);
  }

  @Test
  public void test33()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endFunction();
  }

  @Test
  public void test34()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startUnaryExpr();
  }

  @Test
  public void test35()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startPathExpr();
  }

  @Test
  public void test36()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startProcessingInstructionNodeStep((-1729), "");
  }

  @Test
  public void test37()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startUnionExpr();
  }

  @Test
  public void test38()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startAllNodeStep(915);
  }

  @Test
  public void test39()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endPredicate();
  }

  @Test
  public void test40()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.number(1288.3772689400223);
  }

  @Test
  public void test41()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endEqualityExpr((-1659));
  }

  @Test
  public void test42()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startRelativeLocationPath();
  }

  @Test
  public void test43()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.number((-1035));
  }
}
