/*
 * This file was automatically generated by EvoSuite
 */

package org.saxpath.helpers;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.werken.saxpath.XPathReader;
import org.junit.BeforeClass;
import org.saxpath.SAXPathException;
import org.saxpath.helpers.XPathReaderFactory;

@RunWith(EvoSuiteRunner.class)
public class XPathReaderFactoryEvoSuiteTest {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      XPathReaderFactory xPathReaderFactory0 = new XPathReaderFactory();
      assertNotNull(xPathReaderFactory0);
  }

  @Test
  public void test1()  throws Throwable  {
      XPathReader xPathReader0 = (XPathReader)XPathReaderFactory.createReader();
      assertNotNull(xPathReader0);
  }
}
