/*
 * This file was automatically generated by EvoSuite
 */

package com.werken.saxpath;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import com.werken.saxpath.DefaultXPathHandler;
import org.junit.BeforeClass;

@RunWith(EvoSuiteRunner.class)
public class TestDefaultXPathHandler {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      DefaultXPathHandler.Singleton defaultXPathHandler_Singleton0 = new DefaultXPathHandler.Singleton();
      assertNotNull(defaultXPathHandler_Singleton0);
  }

  @Test
  public void test1()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endPredicate();
  }

  @Test
  public void test2()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endAbsoluteLocationPath();
  }

  @Test
  public void test3()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endCommentNodeStep();
  }

  @Test
  public void test4()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endAdditiveExpr(1209);
  }

  @Test
  public void test5()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startAdditiveExpr();
  }

  @Test
  public void test6()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startMultiplicativeExpr();
  }

  @Test
  public void test7()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endEqualityExpr(748);
  }

  @Test
  public void test8()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startEqualityExpr();
  }

  @Test
  public void test9()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endAndExpr(false);
  }

  @Test
  public void test10()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startTextNodeStep(0);
  }

  @Test
  public void test11()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endRelationalExpr(1416);
  }

  @Test
  public void test12()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startRelationalExpr();
  }

  @Test
  public void test13()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endFilterExpr();
  }

  @Test
  public void test14()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endPathExpr();
  }

  @Test
  public void test15()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startFilterExpr();
  }

  @Test
  public void test16()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startFunction("g>i])?=", "g>i])?=");
  }

  @Test
  public void test17()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endMultiplicativeExpr(0);
  }

  @Test
  public void test18()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startRelativeLocationPath();
  }

  @Test
  public void test19()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startAbsoluteLocationPath();
  }

  @Test
  public void test20()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endProcessingInstructionNodeStep();
  }

  @Test
  public void test21()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startPredicate();
  }

  @Test
  public void test22()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = (DefaultXPathHandler)DefaultXPathHandler.getInstance();
      assertNotNull(defaultXPathHandler0);
  }

  @Test
  public void test23()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endTextNodeStep();
  }

  @Test
  public void test24()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.literal("");
  }

  @Test
  public void test25()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endXPath();
  }

  @Test
  public void test26()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.variableReference("Yc", "Yc");
  }

  @Test
  public void test27()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startPathExpr();
  }

  @Test
  public void test28()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endUnaryExpr((-1));
  }

  @Test
  public void test29()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endNameStep();
  }

  @Test
  public void test30()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.endAllNodeStep();
  }

  @Test
  public void test31()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startUnaryExpr();
  }

  @Test
  public void test32()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endOrExpr(false);
  }

  @Test
  public void test33()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startNameStep(0, "D+ =nws36Y", (String) null);
  }

  @Test
  public void test34()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endUnionExpr(false);
  }

  @Test
  public void test35()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startXPath();
  }

  @Test
  public void test36()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startAllNodeStep(0);
  }

  @Test
  public void test37()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = new DefaultXPathHandler();
      defaultXPathHandler0.startProcessingInstructionNodeStep(1332, ">SImCXZNQ,");
  }

  @Test
  public void test38()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startOrExpr();
  }

  @Test
  public void test39()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.number(1416);
  }

  @Test
  public void test40()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endRelativeLocationPath();
  }

  @Test
  public void test41()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.number(0.0);
  }

  @Test
  public void test42()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startUnionExpr();
  }

  @Test
  public void test43()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startAndExpr();
  }

  @Test
  public void test44()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.startCommentNodeStep(2045);
  }

  @Test
  public void test45()  throws Throwable  {
      DefaultXPathHandler defaultXPathHandler0 = DefaultXPathHandler.Singleton.instance;
      defaultXPathHandler0.endFunction();
  }
}
