/*
 * This file was automatically generated by EvoSuite
 */

package org.saxpath.conformance;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.evosuite.junit.EvoSuiteRunner;
import static org.junit.Assert.*;
import org.junit.BeforeClass;
import org.saxpath.conformance.ConformanceXPathHandler;

@RunWith(EvoSuiteRunner.class)
public class TestConformanceXPathHandler {

  @BeforeClass 
  public static void initEvoSuiteFramework(){ 
    org.evosuite.Properties.REPLACE_CALLS = true; 
  } 


  @Test
  public void test0()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startUnionExpr();
      assertEquals("(0) startUnionExpr()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test1()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endAndExpr(false);
      assertEquals("(0) endAndExpr(false)\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test2()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startXPath();
      assertEquals("(0) startXPath()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test3()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endAllNodeStep();
      assertEquals("(0) endAllNodeStep()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test4()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.number(1886);
      assertEquals("(0) number(1886)\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test5()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.variableReference("4", "endAbsoluteLocationPath()");
      assertEquals("(0) variableReference(\"4:endAbsoluteLocationPath()\")\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test6()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endUnionExpr(true);
      assertEquals("(0) endUnionExpr(true)\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test7()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endMultiplicativeExpr(0);
      assertEquals("(0) endMultiplicativeExpr(0)\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test8()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.literal("-4t6Xh5.`V^Ak~lVI");
      assertEquals("(0) literal(\"-4t6Xh5.`V^Ak~lVI\")\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test9()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startAdditiveExpr();
      assertEquals("(0) startAdditiveExpr()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test10()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endXPath();
      assertEquals("(0) endXPath()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test11()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startRelativeLocationPath();
      assertEquals("(0) startRelativeLocationPath()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test12()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endOrExpr(false);
      assertEquals("(0) endOrExpr(false)\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test13()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startTextNodeStep((-1));
      assertEquals("(0) startTextNodeStep(-1)\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test14()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endUnaryExpr(1021);
      String string0 = conformanceXPathHandler0.toString();
      assertNotNull(string0);
      assertEquals("(0) endUnaryExpr(1021)\n", conformanceXPathHandler0.toString());
      assertEquals("(0) endUnaryExpr(1021)\n", string0);
  }

  @Test
  public void test15()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startOrExpr();
      assertEquals("(0) startOrExpr()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test16()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startProcessingInstructionNodeStep(0, "3_3;^s>;`d%VZH247");
      assertEquals("(0) startProcessingInstructionNodeStep(0, \"3_3;^s>;`d%VZH247\")\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test17()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endFunction();
      assertEquals("(0) endFunction()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test18()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endNameStep();
      assertEquals("(0) endNameStep()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test19()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endCommentNodeStep();
      assertEquals("(0) endCommentNodeStep()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test20()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startPredicate();
      assertEquals("(0) startPredicate()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test21()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endProcessingInstructionNodeStep();
      assertEquals("(0) endProcessingInstructionNodeStep()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test22()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startNameStep(1172, "a[*", "a[*");
      assertEquals("(0) startNameStep(1172, \"a[*\", \"a[*\")\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test23()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startMultiplicativeExpr();
      assertEquals("(0) startMultiplicativeExpr()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test24()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endAdditiveExpr(858);
      assertEquals("(0) endAdditiveExpr(858)\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test25()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endEqualityExpr(0);
      assertEquals("(0) endEqualityExpr(0)\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test26()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startUnaryExpr();
      assertEquals("(0) startUnaryExpr()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test27()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endRelationalExpr(1989);
      assertEquals("(0) endRelationalExpr(1989)\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test28()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startRelationalExpr();
      assertEquals("(0) startRelationalExpr()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test29()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startAndExpr();
      assertEquals("(0) startAndExpr()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test30()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startPathExpr();
      assertEquals("(0) startPathExpr()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test31()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endPredicate();
      assertEquals("(0) endPredicate()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test32()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startFunction("<HE", "<HE");
      assertEquals("(0) startFunction(\"<HE:<HE\")\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test33()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endAbsoluteLocationPath();
      assertEquals("(0) endAbsoluteLocationPath()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test34()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startAbsoluteLocationPath();
      assertEquals("(0) startAbsoluteLocationPath()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test35()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startAllNodeStep((-687));
      assertEquals("(0) startAllNodeStep(-687)\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test36()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.number((double) 0);
      assertEquals("(0) number(0.0)\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test37()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startEqualityExpr();
      assertEquals("(0) startEqualityExpr()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test38()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endPathExpr();
      assertEquals("(0) endPathExpr()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test39()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endRelativeLocationPath();
      assertEquals("(0) endRelativeLocationPath()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test40()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startCommentNodeStep(1);
      assertEquals("(0) startCommentNodeStep(1)\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test41()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endTextNodeStep();
      assertEquals("(0) endTextNodeStep()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test42()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.endFilterExpr();
      assertEquals("(0) endFilterExpr()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test43()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      conformanceXPathHandler0.startFilterExpr();
      assertEquals("(0) startFilterExpr()\n", conformanceXPathHandler0.toString());
  }

  @Test
  public void test44()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      Object object0 = new Object();
      boolean boolean0 = conformanceXPathHandler0.equals(object0);
      assertEquals(false, boolean0);
  }

  @Test
  public void test45()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      boolean boolean0 = conformanceXPathHandler0.equals((Object) conformanceXPathHandler0);
      assertEquals(true, boolean0);
  }

  @Test
  public void test46()  throws Throwable  {
      ConformanceXPathHandler conformanceXPathHandler0 = new ConformanceXPathHandler();
      String string0 = conformanceXPathHandler0.toString();
      assertEquals("", string0);
  }
}
